M48
; DRILL file {KiCad 9.0.6} date 2026-01-26T23:14:37+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-01-26T23:14:37+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0250
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0420
%
G90
G05
T1
X3.5437Y-3.3253
X3.5437Y-3.7433
T2
X3.5827Y-3.5433
M30
